version: "3"

services:
  pingcheck:
    image: sn0am/ping_checks
    container_name: checks
    environment:
    - ping_url=$ping_url
    - ping_interval=$ping_interval
    restart: unless-stopped
